<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-22T13:25:46 IST" name="Default suite" finished-at="2025-08-22T13:26:11 IST" duration-ms="25189">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runner.TestRunner@c86b9e3]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2025-08-22T13:25:46 IST" name="Default test" finished-at="2025-08-22T13:26:11 IST" duration-ms="25189">
      <class name="runner.TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:runner.TestRunner@c86b9e3]" started-at="2025-08-22T13:25:46 IST" name="setUpClass" finished-at="2025-08-22T13:25:47 IST" duration-ms="1306" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1c3259fa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runner.TestRunner@c86b9e3]" started-at="2025-08-22T13:25:47 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-08-22T13:26:10 IST" duration-ms="22873" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Placing the order successfully"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Placeorderr"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stepdefinitions.PlaceOrderStepDefinition.the_user_enter_username_as_and_password_as_and_click_login_button(PlaceOrderStepDefinition.java:43)
at âœ½.the user enter username as "standard_user" and password as "secret_sauce1" and click login button(file:///C:/Users/preeta/Desktop/capgemini/BDD_SauceDemo/src/test/resources/features/placeorder.feature:5)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:runner.TestRunner@c86b9e3]" started-at="2025-08-22T13:26:10 IST" name="tearDownClass" finished-at="2025-08-22T13:26:11 IST" duration-ms="906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
